# Configuration copied from original robot_logic_ncnn_optimized.py

MODEL_PARAM = "best_ncnn_model/model.ncnn.param"
MODEL_BIN = "best_ncnn_model/model.ncnn.bin"

CAMERA_INDEX = 0
CAMERA_WIDTH = 320
CAMERA_HEIGHT = 240
CAMERA_FPS = 15

INPUT_SIZE = 256
DETECT_EVERY = 3

SAVE_EVERY = 15
SAVE_DIR = "run_images"

NCNN_THREADS = 4
PRINT_EVERY = 15

CONF_THRES = 0.35
NMS_THRES = 0.45

KP_TURN = 0.003

MAX_SPEED = 1.0
MIN_SPEED = -1.0

MAX_LOST_FRAMES = 30
REID_DISTANCE_PX = 120
STABLE_FRAMES_REQUIRED = 3

DEAD_ZONE_PX = 40

TARGET_BOX_HEIGHT_RATIO = 0.90
KP_FORWARD = 1.2
MIN_FORWARD_SPEED = 0.0
MAX_FORWARD_SPEED = 0.8

KP_TILT = 0.04
DESIRED_TOP_Y_RATIO = 0.10
TILT_DEAD_ZONE_PX = 25
CAMERA_TILT_MIN = 40
CAMERA_TILT_MAX = 140
CAMERA_TILT_INITIAL = 90
TILT_STOP_MARGIN = 3
